import { Injectable } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { Observable } from 'rxjs';

export interface Payment {
  _id?: string;
  amount: number;
  paymentType: string;
  paymentDate: string | Date;
  remarks?: string;
}

export interface Invoice {
  _id?: string;
  srNo?: number; // Auto-generated by backend
  clientName: string;
  itemDescription: string;
  invoiceNo: string;
  invoiceDate: string | Date;
  invoiceAmount: number;
  currency: 'USD' | 'EUR' | 'GBP' | 'INR' | 'CNY' | 'JPY' | 'AUD' | 'CAD' | 'CHF' | 'AED';
  invoiceType: 'Service' | 'Product' | 'License';
  transferAmount: number;
  bankName: string;
  bankRefNumber?: string;
  bankTransferDate?: string;
  status: 'Paid' | 'Pending' | 'Partial' | 'Unpaid';
  remarks?: string;
  // Material tracking fields
  materialReceived?: 'Yes' | 'No';
  receiptDate?: string | Date;
  courierName?: string;
  billingCustomer?: string;
  payments?: Payment[];
}

export interface ApiResponse<T> {
  success: boolean;
  data?: T;
  count?: number;
  message?: string;
}

@Injectable({
  providedIn: 'root'
})
export class PaymentDataService {
  private apiUrl = 'http://localhost:3000/api/invoices';

  constructor(private http: HttpClient) { }

  getAllInvoices(): Observable<ApiResponse<Invoice[]>> {
    return this.http.get<ApiResponse<Invoice[]>>(this.apiUrl);
  }

  getInvoiceById(id: string): Observable<ApiResponse<Invoice>> {
    return this.http.get<ApiResponse<Invoice>>(`${this.apiUrl}/${id}`);
  }

  createInvoice(invoice: Partial<Invoice>): Observable<ApiResponse<Invoice>> {
    return this.http.post<ApiResponse<Invoice>>(this.apiUrl, invoice);
  }

  updateInvoice(id: string, invoice: Partial<Invoice>): Observable<ApiResponse<Invoice>> {
    return this.http.put<ApiResponse<Invoice>>(`${this.apiUrl}/${id}`, invoice);
  }

  deleteInvoice(id: string): Observable<ApiResponse<Invoice>> {
    return this.http.delete<ApiResponse<Invoice>>(`${this.apiUrl}/${id}`);
  }

  // Payment methods
  addPayment(invoiceId: string, payment: Partial<Payment>): Observable<ApiResponse<Invoice>> {
    return this.http.post<ApiResponse<Invoice>>(`${this.apiUrl}/${invoiceId}/payments`, payment);
  }

  getPayments(invoiceId: string): Observable<ApiResponse<any>> {
    return this.http.get<ApiResponse<any>>(`${this.apiUrl}/${invoiceId}/payments`);
  }

  deletePayment(invoiceId: string, paymentId: string): Observable<ApiResponse<Invoice>> {
    return this.http.delete<ApiResponse<Invoice>>(`${this.apiUrl}/${invoiceId}/payments/${paymentId}`);
  }

  // Material tracking methods
  updateMaterialInfo(invoiceId: string, materialData: {
    materialReceived?: 'Yes' | 'No';
    receiptDate?: string | Date;
    courierName?: string;
    billingCustomer?: string;
  }): Observable<ApiResponse<Invoice>> {
    return this.http.put<ApiResponse<Invoice>>(`${this.apiUrl}/${invoiceId}/material`, materialData);
  }
}
